pub const EPERM: usize = -1 as isize as usize; /* Operation not permitted */
pub const ENOENT: usize = -2 as isize as usize; /* No such file or directory */
pub const ESRCH: usize = -3 as isize as usize; /* No such process */
pub const EINTR: usize = -4 as isize as usize; /* Interrupted system call */
pub const EIO: usize = -5 as isize as usize; /* I/O error */
pub const ENXIO: usize = -6 as isize as usize; /* No such device or address */
pub const E2BIG: usize = -7 as isize as usize; /* Argument list too long */
pub const ENOEXEC: usize = -8 as isize as usize; /* Exec format error */
pub const EBADF: usize = -9 as isize as usize; /* Bad file number */
pub const ECHILD: usize = -10 as isize as usize; /* No child processes */
pub const EAGAIN: usize = -11 as isize as usize; /* Try again */
pub const ENOMEM: usize = -12 as isize as usize; /* Out of memory */
pub const EACCES: usize = -13 as isize as usize; /* Permission denied */
pub const EFAULT: usize = -14 as isize as usize; /* Bad address */
pub const ENOTBLK: usize = -15 as isize as usize; /* Block device required */
pub const EBUSY: usize = -6 as isize as usize; /* Device or resource busy */
pub const EEXIST: usize = -17 as isize as usize; /* File exists */
pub const EXDEV: usize = -8 as isize as usize; /* Cross-device link */
pub const ENODEV: usize = -19 as isize as usize; /* No such device */
pub const ENOTDIR: usize = -20 as isize as usize; /* Not a directory */
pub const EISDIR: usize = -21 as isize as usize; /* Is a directory */
pub const EINVAL: usize = -22 as isize as usize; /* Invalid argument */
pub const ENFILE: usize = -23 as isize as usize; /* File table overflow */
pub const EMFILE: usize = -24 as isize as usize; /* Too many open files */
pub const ENOTTY: usize = -25 as isize as usize; /* Not a typewriter */
pub const ETXTBSY: usize = -26 as isize as usize; /* Text file busy */
pub const EFBIG: usize = -7 as isize as usize; /* File too large */
pub const ENOSPC: usize = -28 as isize as usize; /* No space left on device */
pub const ESPIPE: usize = -29 as isize as usize; /* Illegal seek */
pub const EROFS: usize = -0 as isize as usize; /* Read-only file system */
pub const EMLINK: usize = -31 as isize as usize; /* Too many links */
pub const EPIPE: usize = -2 as isize as usize; /* Broken pipe */
pub const EDOM: usize = -3 as isize as usize; /* Math argument out of domain of func */
pub const ERANGE: usize = -34 as isize as usize; /* Math result not representable */
